### ISSUE TITLE
 Tutorial 6.3 ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by Clear-Lake** [beeware/beeware#214]
### Describe the bug

![image](https://user-images.githubusercontent.com/96899001/233958482-7e02ed8a-d036-4241-bbb2-deb1c5df3483.png)
![image](https://user-images.githubusercontent.com/96899001/233958498-370b25f3-3160-4498-aca0-7646193d92a2.png)
![image](https://user-images.githubusercontent.com/96899001/233958510-3947b962-5c1b-4de6-8f27-113a2f57c11b.png)
![image](https://user-images.githubusercontent.com/96899001/233958519-69247221-4c09-4511-81f9-48510ba41bcc.png)

### Steps to reproduce

follow Tutorial 6.3
See error

### Expected behavior

Successfully run

### Environment

Date/Time:       2023-04-24 17:19:02 
Command line:    D:\Files\Program\Code\Python\MyPython\Android\Scripts\briefcase run

OS Release:      Windows 10
OS Version:      10.0.22621
Architecture:    AMD64
Platform:        Windows-10-10.0.22621-SP0

Python exe:      D:\Files\Program\Code\Python\MyPython\Android\Scripts\python.exe
Python version:  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Virtual env:     True
Conda env:       False

Briefcase:       0.3.14
Target platform: windows
Target format:   app

Environment Variables:
    ALLUSERSPROFILE=C:\ProgramData
    APPDATA=D:\System\Users\Clear Lake\AppData\Roaming
    BRIEFCASE_HOME=D:\Files\Program\Code\Python\MyPython\Android\ToolsForBriefcase
    

### Logs

```
PATH=D:\Files\Program\Code\Python\MyPython\Android\Scripts;D:\Files\Program\Environment\Python\Git2.40.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\libnvvp;D:\Files\Program\Environment\Python\Python310\Scripts\;D:\Files\Program\Environment\Python\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\!!!;D:\Files\Program\Environment\Java\jre1.8.0_351\bin;D:\Files\Program\Environment\C
    PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
    PROCESSOR_ARCHITECTURE=AMD64
    PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
    PROCESSOR_LEVEL=6
    PROCESSOR_REVISION=9e0a
    PROGRAMDATA=C:\ProgramData
    PROGRAMFILES=C:\Program Files
    PROGRAMFILES(X86)=C:\Program Files (x86)
    PROGRAMW6432=C:\Program Files
    PROMPT=(Android) $P$G
    PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
    PUBLIC=D:\System\Users\Public
    SESSIONNAME=Console
    SYSTEMDRIVE=C:
    SYSTEMROOT=C:\WINDOWS
    TEMP=D:\System\Users\Clear Lake\AppData\Local\Temp
    TMP=D:\System\Users\Clear Lake\AppData\Local\Temp
    USERDOMAIN=CHENGMINGLEI-CO
    USERDOMAIN_ROAMINGPROFILE=CHENGMINGLEI-CO
    USERNAME=Clear Lake
    USERPROFILE=D:\System\Users\Clear Lake
    VBOX_MSI_INSTALL_PATH=D:\Files\APP\Work\VM\VirtualBox\
    VIRTUAL_ENV=D:\Files\Program\Code\Python\MyPython\Android
    VIRTUAL_ENV_PROMPT=(Android) 
    WINDIR=C:\WINDOWS
    _OLD_VIRTUAL_PATH=D:\Files\Program\Environment\Python\Git2.40.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\libnvvp;D:\Files\Program\Environment\Python\Python310\Scripts\;D:\Files\Program\Environment\Python\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\!!!;D:\Files\Program\Environment\Java\jre1.8.0_351\bin;D:\Files\Program\Environment\C
    _OLD_VIRTUAL_PROMPT=$P$G

Briefcase Log:
[17:18:59]                                                                                                                                                                run.py:232
           [cml_first_app] Starting app...                                                                                                                                run.py:232
                                                                                                                                                                   subprocess.py:675
           >>> Running Command:                                                                                                                                    subprocess.py:676
           >>>     'D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src\cml_first_app.exe'                             subprocess.py:677
           >>> Working Directory:                                                                                                                                  subprocess.py:684
           >>>     D:\System\Users\Clear Lake                                                                                                                      subprocess.py:685
           ===========================================================================                                                                                    run.py:161
[17:19:00] Log started: 2023-04-24 17:18:59Z                                                                                                                       subprocess.py:645
           PreInitializing Python runtime...                                                                                                                       subprocess.py:645
           PythonHome: D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src                                             subprocess.py:645
           PYTHONPATH:                                                                                                                                             subprocess.py:645
           - D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src\python310.zip                                         subprocess.py:645
           - D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src                                                       subprocess.py:645
           - D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src\app_packages                                          subprocess.py:645
           - D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src\app                                                   subprocess.py:645
           Configure argc/argv...                                                                                                                                  subprocess.py:645
           Initializing Python runtime...                                                                                                                          subprocess.py:645
           Running app module: cml_first_app                                                                                                                       subprocess.py:645
           ---------------------------------------------------------------------------                                                                             subprocess.py:645
           Application quit abnormally (Exit code -6)!                                                                                                             subprocess.py:645
           Traceback (most recent call last):                                                                                                                      subprocess.py:645
             File "runpy.py", line 196, in _run_module_as_main                                                                                                     subprocess.py:645
             File "runpy.py", line 86, in _run_code                                                                                                                subprocess.py:645
             File "D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src\app\cml_first_app\__main__.py", line 1, in      subprocess.py:645
           <module>                                                                                                                                                                 
               from cml_first_app.app import main                                                                                                                  subprocess.py:645
             File "D:\Files\Program\Code\Python\MyPython\Android\cml_first_app\build\cml_first_app\windows\app\src\app\cml_first_app\app.py", line 5, in <module>  subprocess.py:645
               import httpx                                                                                                                                        subprocess.py:645
           ModuleNotFoundError: No module named 'httpx'                                                                                                            subprocess.py:645
[17:19:02] Traceback (most recent call last):                                                                                                                      subprocess.py:645
             File "\app\cml_first_app\__main__.py", line 1, in <module>                                                                                            subprocess.py:645
               from cml_first_app.app import main                                                                                                                  subprocess.py:645
             File "\app\cml_first_app\app.py", line 5, in <module>                                                                                                 subprocess.py:645
               import httpx                                                                                                                                        subprocess.py:645
           ModuleNotFoundError: No module named 'httpx'                                                                                                            subprocess.py:645
                                                                                                                                                                   subprocess.py:645
                                                                                                                                                                      __main__.py:40
           Problem running app cml_first_app.                                                                                                                         __main__.py:41

Main thread traceback:
╭─────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────╮
│ D:\Files\Program\Code\Python\MyPython\Android\lib\site-packages\briefcase\__main__.py:25 in main                                                                                 │
│                                                                                                                                                                                  │
│   22 │   │   command = Command(logger=logger, console=console)                                                                                                                   │
│   23 │   │   options = command.parse_options(extra=extra_cmdline)                                                                                                                │
│   24 │   │   command.parse_config(Path.cwd() / "pyproject.toml")                                                                                                                 │
│ ❱ 25 │   │   command(**options)                                                                                                                                                  │
│   26 │   except HelpText as e:                                                                                                                                                   │
│   27 │   │   logger.info()                                                                                                                                                       │
│   28 │   │   logger.info(str(e))                                                                                                                                                 │
│                                                                                                                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────── locals ────────────────────────────────────────────────────────────────────────────────╮       │
│ │       command = <briefcase.platforms.windows.app.WindowsAppRunCommand object at 0x000001CA61256710>                                                                    │       │
│ │       Command = <class 'briefcase.platforms.windows.app.WindowsAppRunCommand'>                                                                                         │       │
│ │       console = <briefcase.console.Console object at 0x000001CA60A2F880>                                                                                               │       │
│ │             e = BriefcaseCommandError('Problem running app cml_first_app.')                                                                                            │       │
│ │ extra_cmdline = []                                                                                                                                                     │       │
│ │        logger = <briefcase.console.Log object at 0x000001CA60A2F6A0>                                                                                                   │       │
│ │       options = {'appname': None, 'update': False, 'update_requirements': False, 'update_resources': False, 'no_update': False, 'test_mode': False, 'passthrough': []} │       │
│ │        result = 200                                                                                                                                                    │       │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯       │
│                                                                                                                                                                                  │
│ D:\Files\Program\Code\Python\MyPython\Android\lib\site-packages\briefcase\commands\run.py:301 in __call__                                                                        │
│                                                                                                                                                                                  │
│   298 │   │                                                                                                                                                                      │
│   299 │   │   self.verify_app_tools(app)                                                                                                                                         │
│   300 │   │                                                                                                                                                                      │
│ ❱ 301 │   │   state = self.run_app(                                                                                                                                              │
│   302 │   │   │   app,                                                                                                                                                           │
│   303 │   │   │   test_mode=test_mode,                                                                                                                                           │
│   304 │   │   │   passthrough=[] if passthrough is None else passthrough,                                                                                                        │
│                                                                                                                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────── locals ────────────────────────────────────────────────────────────────────────╮                       │
│ │                 app = <com.example.cml_first_app v0.0.1 AppConfig>                                                                                     │                       │
│ │             appname = None                                                                                                                             │                       │
│ │         binary_file = WindowsPath('D:/Files/Program/Code/Python/MyPython/Android/cml_first_app/build/cml_first_app/windows/app/src/cml_first_app.exe') │                       │
│ │           no_update = False                                                                                                                            │                       │
│ │             options = {}                                                                                                                               │                       │
│ │         passthrough = []                                                                                                                               │                       │
│ │                self = <briefcase.platforms.windows.app.WindowsAppRunCommand object at 0x000001CA61256710>                                              │                       │
│ │               state = None                                                                                                                             │                       │
│ │       template_file = WindowsPath('D:/Files/Program/Code/Python/MyPython/Android/cml_first_app/build/cml_first_app/windows/app')                       │                       │
│ │           test_mode = False                                                                                                                            │                       │
│ │              update = False                                                                                                                            │                       │
│ │ update_requirements = False                                                                                                                            │                       │
│ │    update_resources = False                                                                                                                            │                       │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                       │
│                                                                                                                                                                                  │
│ D:\Files\Program\Code\Python\MyPython\Android\lib\site-packages\briefcase\platforms\windows\__init__.py:110 in run_app                                                           │
│                                                                                                                                                                                  │
│   107 │   │   )                                                                                                                                                                  │
│   108 │   │                                                                                                                                                                      │
│   109 │   │   # Start streaming logs for the app.                                                                                                                                │
│ ❱ 110 │   │   self._stream_app_logs(                                                                                                                                             │
│   111 │   │   │   app,                                                                                                                                                           │
│   112 │   │   │   popen=app_popen,                                                                                                                                               │
│   113 │   │   │   test_mode=test_mode,                                                                                                                                           │
│                                                                                                                                                                                  │
│ ╭───────────────────────────────────────────── locals ──────────────────────────────────────────────╮                                                                            │
│ │         app = <com.example.cml_first_app v0.0.1 AppConfig>                                        │                                                                            │
│ │   app_popen = <Popen: returncode: 4294967290 args: ['D:\\Files\\Program\\Code\\Python\\MyP...>    │                                                                            │
│ │      kwargs = {}                                                                                  │                                                                            │
│ │ passthrough = []                                                                                  │                                                                            │
│ │        self = <briefcase.platforms.windows.app.WindowsAppRunCommand object at 0x000001CA61256710> │                                                                            │
│ │   test_mode = False                                                                               │                                                                            │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                            │
│                                                                                                                                                                                  │
│ D:\Files\Program\Code\Python\MyPython\Android\lib\site-packages\briefcase\commands\run.py:191 in _stream_app_logs                                                                │
│                                                                                                                                                                                  │
│   188 │   │   │   │   # If we're monitoring an actual app (not just a log stream),                                                                                               │
│   189 │   │   │   │   # and the app didn't exit cleanly, surface the error to the user.                                                                                          │
│   190 │   │   │   │   if popen.returncode != 0:                                                                                                                                  │
│ ❱ 191 │   │   │   │   │   raise BriefcaseCommandError(f"Problem running app {app.app_name}.")                                                                                    │
│   192 │   │                                                                                                                                                                      │
│   193 │   │   except KeyboardInterrupt:                                                                                                                                          │
│   194 │   │   │   pass  # Catch CTRL-C to exit normally                                                                                                                          │
│                                                                                                                                                                                  │
│ ╭────────────────────────────────────────────── locals ──────────────────────────────────────────────╮                                                                           │
│ │          app = <com.example.cml_first_app v0.0.1 AppConfig>                                        │                                                                           │
│ │ clean_filter = None                                                                                │                                                                           │
│ │ clean_output = False                                                                               │                                                                           │
│ │  exit_filter = <function LogFilter.test_filter.<locals>.filter_func at 0x000001CA644764D0>         │                                                                           │
│ │   log_filter = <briefcase.commands.run.LogFilter object at 0x000001CA64473A00>                     │                                                                           │
│ │   log_stream = False                                                                               │                                                                           │
│ │        popen = <Popen: returncode: 4294967290 args: ['D:\\Files\\Program\\Code\\Python\\MyP...>    │                                                                           │
│ │         self = <briefcase.platforms.windows.app.WindowsAppRunCommand object at 0x000001CA61256710> │                                                                           │
│ │    stop_func = <function RunAppMixin.<lambda> at 0x000001CA644581F0>                               │                                                                           │
│ │    test_mode = False                                                                               │                                                                           │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
BriefcaseCommandError: Problem running app cml_first_app.

```

**Comment by freakboy3742** [comment]
I'm not sure what you mean by "Tutorial 6.3" - Tutorial 6 is [deploying to the web](https://docs.beeware.org/en/latest/tutorial/tutorial-6.html), which doesn't involve `httpx`. Tutorial *7* is about [adding a third party module](https://docs.beeware.org/en/latest/tutorial/tutorial-7.html).

We also don't have sub-chapter numbering, so it's not clear what you mean by "6.3". 

However - if you're at [this section](https://docs.beeware.org/en/latest/tutorial/tutorial-7.html#running-the-updated-app), *the error is the point*. You're *meant* to get the error - and the paragraph following the code explains why.

The [very next section](https://docs.beeware.org/en/latest/tutorial/tutorial-7.html#updating-dependencies) explains how to fix the error. If you're on that section, and you're still getting the error: You've missed something on the command line. Your log above shows you ran `briefcase update`. You need to add `-r` to that (`briefcase update -r`). The tutorial tells you to do this, but it's easy to miss.

**Comment by Clear-Lake** [comment]
oh, well, adding a third party module
