### ISSUE TITLE
Win/docker/Ubuntu errors

### ISSUE THREAD

**Issue by joelfreybott** [beeware/beeware#34]
I've tried to use the beeware tutorial many times with planty of different ways. The following errors keep coming up:

Windows 10:

Collecting pythonnet
  Using cached pythonnet-2.4.0.tar.gz (1.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jf\beeware-tutorial\beeware-venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jf\\AppData\\Local\\Temp\\pip-install-_5p6efq6\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\jf\\AppData\\Local\\Temp\\pip-install-_5p6efq6\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jf\AppData\Local\Temp\pip-install-_5p6efq6\pythonnet\pip-egg-info'
         cwd: C:\Users\jf\AppData\Local\Temp\pip-install-_5p6efq6\pythonnet\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jf\AppData\Local\Temp\pip-install-_5p6efq6\pythonnet\setup.py", line 18, in <module>
        from wheel import bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

############################################################################

docker:

after installing beeware as explained in docker (ubuntu 16.04)

root@90bdda6ca734:/# briefcase new
bash: briefcase: command not found

############################################################################

Ubuntu 16.04 in virtualbox:

(beeware-venv) joel@joel-vm-ubuntu:~/beeware-tutorial$ briefcase new
Traceback (most recent call last):
  File "/home/joel/beeware-tutorial/beeware-venv/bin/briefcase", line 7, in <module>
    from briefcase.__main__ import main
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/briefcase/__main__.py", line 3, in <module>
    from .cmdline import parse_cmdline
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/briefcase/cmdline.py", line 6, in <module>
    from briefcase.commands import DevCommand, NewCommand
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/briefcase/commands/__init__.py", line 1, in <module>
    from .build import BuildCommand  # noqa
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/briefcase/commands/build.py", line 5, in <module>
    from .base import BaseCommand, full_kwargs
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/briefcase/commands/base.py", line 15, in <module>
    from cookiecutter.main import cookiecutter
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/cookiecutter/main.py", line 15, in <module>
    from .generate import generate_context, generate_files
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/cookiecutter/generate.py", line 15, in <module>
    from jinja2 import FileSystemLoader
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/jinja2/__init__.py", line 8, in <module>
    from .bccache import BytecodeCache
  File "/home/joel/beeware-tutorial/beeware-venv/lib/python3.5/site-packages/jinja2/bccache.py", line 207
    dirname = f"_jinja2-cache-{os.getuid()}"
                                           ^
SyntaxError: invalid syntax

**Comment by freakboy3742** [comment]
Thanks again for the report (and for persisting even though you're hitting these problems!)

There's three different errors going on here.

The first is `No module named 'wheel'`. This error is specifically called out in the tutorial instructions for Windows (the first Windows tab of [tutorial 1 - your first app](https://docs.beeware.org/en/latest/tutorial/tutorial-1.html)).  The problem is that one of BeeWare's dependencies (pythonnet) doesn't currently support Python 3.8. If you use a different version of Python (3.7 would be my current recommendation), you'll have more success. I'll clarify the instructions to point out that Python 3.8 is a problem on Windows.

The second error (`briefcase: command not found`) is a flaw in the BeeWare tutorial instructions. It neglects to include `git` and `python3-pip` as part of the system packages, and to specify `--pre` when installing Briefcase. Apologies for the confusion; I'll update the documentation shortly.

The third error (`SyntaxError: invalid syntax`) is the result of running code that contains an f-string in Python 3.5. This appears to be due to the release of Jinja2 3.0.0a1 on Feb 6, which removed support for Python 3.5. Correcting this will require an update to the packaging of Briefcase itself. I've opened beeware/briefcase#305 to track the problem. In the interim, if you run: 
```
$ python3 -m pip install  -U "Jinja2<3.0"
```
it will downgrade Jinja2 to a version that is Python3.5 compatible, and you should be able to proceed. Apologies again for the confusion.

**Comment by freakboy3742** [comment]
FYI: I've just pushed Briefcase 0.3.0.dev7 and updated the BeeWare tutorial to correct the Docker instructions and better clarify the Python version requirements.
