### ISSUE TITLE
Tutorial App (Helloworld) not responding (windows 10, python3.8)

### ISSUE THREAD

**Issue by cr1val** [beeware/beeware#51]
In tutorial Step 1, when I do **briefcase dev** I get the following:

```
(beeware-venv) D:\prog\beeware-tutorial\helloworld>briefcase dev

[helloworld] Installing dependencies...
Requirement already up-to-date: toga-winforms>=0.3.0.dev18 in d:\prog\beeware-tutorial\beeware-venv\lib\site-packages (0.3.0.dev19)
Requirement already satisfied, skipping upgrade: toga-core==0.3.0.dev19 in d:\prog\beeware-tutorial\beeware-venv\lib\site-packages (from toga-winforms>=0.3.0.dev18) (0.3.0.dev19)
Collecting pythonnet
  Using cached pythonnet-2.4.0.tar.gz (1.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\prog\beeware-tutorial\beeware-venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ventas\\AppData\\Local\\Temp\\pip-install-bbm9u1cw\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ventas\\AppData\\Local\\Temp\\pip-install-bbm9u1cw\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Ventas\AppData\Local\Temp\pip-pip-egg-info-fn5afizt'
         cwd: C:\Users\Ventas\AppData\Local\Temp\pip-install-bbm9u1cw\pythonnet\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ventas\AppData\Local\Temp\pip-install-bbm9u1cw\pythonnet\setup.py", line 18, in <module>
        from wheel import bdist_wheel
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip was unable to connect to the PyPI server.

(beeware-venv) D:\prog\beeware-tutorial\helloworld>
```
I try to downgrade python to 3.7 and after installing pythonnet-2.4.1.dev0-cp38-cp38-win32.whl

The app start, but not respond (NOT RESPONDING)

**Comment by freakboy3742** [comment]
If you're getting the "not responding" behavior, it means that whatever you're done to "downgrade" isn't sufficient - you're still running Python3.8.

You'll need to go right back to the start, recreating the virtual environment, and re-installing everything. Python virtual environments are are bound to Python versions, so to change your Python version you need to recreate your virtual environment. 

When you do this, you *won't* need to manually install the Python.net wheel - it will be automatically installed as part of the tutorial.
