### ISSUE TITLE
Tutorial - 'briefcase run' error (MacOS Catalina 10.15.4, Python 3.7)

### ISSUE THREAD

**Issue by jchenj** [beeware/beeware#53]
As I worked through the tutorial, I got the following error when I used `briefcase run` to run the initial version of the app (tutorial pg. 3) and the updated version (pg. 4). 

````
(.env) jchen@ribka:~/Desktop/FOSS/beeware/beeware-tutorial/helloworld$ briefcase run

[helloworld] Starting app...

LSOpenURLsWithRole() failed with error -10810 for the file /Users/jchen/Desktop/FOSS/beeware/beeware-tutorial/helloworld/macOS/Hello World/Hello World.app.

Unable to start app helloworld.
````

The app ran successfully in developer mode and in the DMG installed copy for each version. `briefcase run` did work when I ran the iOS version:

````
(.env) jchen@ribka:~/Desktop/FOSS/beeware/beeware-tutorial/helloworld$ briefcase run iOS -d "iPhone 11::iOS 13.5"
[helloworld] Starting app on an iPhone 11 running iOS iOS 13.5 (device UDID 51B27672-3FE6-4715-AC04-07C80B33156F)
Booting iPhone 11 simulator running iOS iOS 13.5...
Opening iPhone 11 simulator running iOS iOS 13.5...
[helloworld] Uninstalling old app version...
[helloworld] Installing new app version...
[helloworld] Starting app...
com.example.helloworld: 17024
````

**Comment by freakboy3742** [comment]
Thanks for the report - and sorry to hear that you hit a problem!

The "LSOpenURLsWithRole()" error isn't a very nice one - but it's macOS saying "something was so wrong with this app that I couldn't even start it". Unfortunately, it doesn't provide any context or detail beyond that. Fixing this so that users like yourself get a more helpful error message is [an open bug that we want to address](https://github.com/beeware/briefcase-macOS-app-template/issues/1).

The good news is that you can trick macOS to give you more detail. A macOS app is nothing more than a directory in a very specific format - so you can manually start the app from the command line, which means you get to see what is going wrong.

From your project directory (the one with `pyproject.toml`), run:
```
$ ./macOS/Hello\ World/Hello\ World.app/Contents/MacOS/Hello\ World
```
That will start the app in the same way as double clicking on the icon (or using `briefcase run`); but you'll get to see any console output related to the crash. Hopefully this will give us a little more detail on what is going wrong.

**Comment by jchenj** [comment]
Thanks for the context & suggestion! 

I ran the app successfully from the command line with the command you provided. The app also runs fine when I double-click on the icon in the finder - it's just `briefcase run` that doesn't work, for some reason.

About the [open bug you mentioned](https://github.com/beeware/briefcase-macOS-app-template/issues/1), I'm looking for first bug to work on. I have about two years experience programming in Python, and just getting started in open source. While this issue's not labeled first-timers-only, if you think it might be a good fit for a newcomer with some experience error handling in Python scripts, let me know and I'll be happy to look into it. If not, no worries - I'll be looking at the first-timers labeled issues & find one there!

**Comment by freakboy3742** [comment]
Hrm - the fact that it's only `briefcase run` is quite concerning. Two more diagnostic things to try:

1. `open macOS/Hello\ World/Hello\ World.app` - that's the command-line version of double clicking on the app icon, and *should* be what briefcase is doing programmatically
2. Get out the scalpel and start doing surgery :-) The implementation of the run command is [here](https://github.com/beeware/briefcase/blob/master/src/briefcase/platforms/macOS/app.py#L57) - try setting a breakpoint around that line and see what you can find by poking around the command, the environment, the return codes from `subprocess.call`, and so on.

As for contributing code: modifying the app template could definitely be a good place to start; don't let the lack of a 'first-timers' tag stop you if you think the problem looks interesting.

As background on that issue: the problem isn't strictly one of Python programming. It's capturing and reporting when Python itself fails. The `Contents/MacOS/App Name` script is a command line script that starts the Python interpreter - but what happens when that invocation fails? What happens if the Python interpreter itself wont start (not a common occurrence, but it *has* been reported in the past when the support package has been corrupted, or the startup script has a path problem)? And, of course, what happens when the Python script fails (due to a syntax error in the script, or a runtime error like a missing dependency)? 

For all those modes of failure (and any others you can think of), we need to catch the failure, and show a dialog box to inform the user of the problem - ideally, without assuming a Python interpreter is present and working, and without modifying the users application code. You might find [this page](https://osxdaily.com/2016/09/06/trigger-alert-dialog-mac-via-command-line/) helpful for the dialog display piece.

**Comment by jchenj** [comment]
Thanks for the suggestions & pointers! The app ran successfully with `open macOS/Hello\ World/Hello\ World.app`. I'm starting on the scalpel & surgery step, and will keep you posted on what I find. 

I'll also look into modifying the app template, starting with the notes you provided. I'll let you know how it goes and if/when related questions come up.

**Comment by jchenj** [comment]
@freakboy3742, could you help me out on a newbie question related to point 2 in your diagnostic pointers (copied below)? I'm not seeing the implementation of the `briefcase run` command within the files in my beeware-tutorial project files (which include the venv & helloworld directories.) Is this file supposed to be within my tutorial project files, or is there something else I need to do to link my tutorial project with the Briefcase source code? 

> The implementation of the run command is [here](https://github.com/beeware/briefcase/blob/master/src/briefcase/platforms/macOS/app.py#L57) - try setting a breakpoint around that line and see what you can find by poking around the command, the environment, the return codes from subprocess.call, and so on)

**Comment by freakboy3742** [comment]
The run command is part of the implementation of Briefcase itself, rather than your app. The piece you're looking to debug is the code that is executing your app, rather than a problem with the app that has been generated. After all - at this point, it looks like it runs fine everywhere *except* from within Briefcase, so it's not a problem with the app itself!

**Comment by jchenj** [comment]
Thanks for the clarification! Here's a status update: 

I've narrowed the issue down to something related to my virtual env (details below). For next steps, I'm thinking to create a fresh venv and try running from there, in case the issue is with the empty venv, and then adding back in the required packages one by one to see if I can isolate which one might be causing the issue.

If you have any other thoughts/suggestions on this, let me know! 

**Process so far**
- The traceback from running the module showed a CalledProcessError thrown by `run_app`:
````
/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/.env/bin/python -m briefcase run

[helloworld] Starting app...
LSOpenURLsWithRole() failed with error -10810 for the file /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/__main__.py", line 26, in <module>
    main()
  File "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/__main__.py", line 11, in main
    command(**options)
  File "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/commands/run.py", line 77, in __call__
    state = self.run_app(app, **full_options(state, options))
  File "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/platforms/macOS/app.py", line 62, in run_app
    check=True,
  File "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/integrations/subprocess.py", line 66, in run
    **self.final_kwargs(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['open', '/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app']' returned non-zero exit status 1.
````
- I pulled out lines 57-63 of the run implementation into a script and replaced `self.binary_path(app)` with the app's absolute path:
````
import subprocess

subprocess.run(
    [
        'open',
        "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app"
        # self.binary_path(app),
    ],
    check=True,
)
````
- The app runs successfully when I run the script outside of the venv:
````
jchen@ribka:~/Desktop/FOSS/beeware/briefcase2/briefcase$ python3 /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/test_run.py 
jchen@ribka:~/Desktop/FOSS/beeware/briefcase2/briefcase$ 
````
- But the app doesn't run when I run the script inside the venv:
````
jchen@ribka:~/Desktop/FOSS/beeware/briefcase2/briefcase$ . .env/bin/activate
(.env) jchen@ribka:~/Desktop/FOSS/beeware/briefcase2/briefcase$ python3 /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/test_run.py 
LSOpenURLsWithRole() failed with error -10810 for the file /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app.
Traceback (most recent call last):
  File "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/briefcase/test_run.py", line 10, in <module>
    check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['open', '/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app']' returned non-zero exit status 1.
````
- I tried replacing the tutorial app with another app (I chose Script Editor arbitrarily) and it ran successfully from both inside and outside the venv. The script in this case was:
````
import subprocess

subprocess.run(
    [
        'open',
        "/System/Applications/Utilities/Script Editor.app"
        # "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app"
        # self.binary_path(app),
    ],
    check=True,
)
````
- For reference, my venv currently contains the packages below. To my knowledge this is just the development version of Briefcase, along with all its requirements:
````
(.env) jchen@ribka:~/Desktop/FOSS/beeware/briefcase2/briefcase$ pip list
Package            Version    Location                                                  
------------------ ---------- ----------------------------------------------------------
appdirs            1.4.4      
arrow              0.15.6     
binaryornot        0.4.4      
biplist            1.0.3      
briefcase          0.3.0      /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src
certifi            2020.4.5.1 
chardet            3.0.4      
click              7.1.2      
cookiecutter       1.7.2      
distlib            0.3.0      
dmgbuild           1.3.3      
ds-store           1.1.2      
filelock           3.0.12     
gitdb              4.0.5      
GitPython          3.1.3      
idna               2.9        
importlib-metadata 1.6.0      
Jinja2             2.11.2     
jinja2-time        0.2.0      
mac-alias          2.0.7      
MarkupSafe         1.1.1      
packaging          20.4       
pip                19.0.3     
pluggy             0.13.1     
poyo               0.5.0      
py                 1.8.1      
pyparsing          2.4.7      
python-dateutil    2.8.1      
python-slugify     4.0.0      
requests           2.23.0     
setuptools         40.8.0     
six                1.15.0     
smmap              3.0.4      
text-unidecode     1.3        
toml               0.10.1     
tox                3.15.1     
urllib3            1.25.9     
virtualenv         20.0.21    
zipp               3.1.0      
````

**Comment by freakboy3742** [comment]
Ok - that's interesting: it's being *inside* the virtual environment that is causing the problem. That's surprising to me, because the app *should* be running in a clean environment that isn't affected by the environment where Briefcase is running. Clearly there's *something* leaking into the execution.

Another test: does running `open /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app` yield the same behavior, depending on whether you're inside or outside the virtual environment?

The next set of checks will be related to the way the app is actually starting. If you open `Hello World.app/Contents/MacOS/Hello World`, you'll see it's actually a bash script that starts the Python interpreter. So:

 * If you change that script to a simple "echo hello" - does it run? (it obviously won't start the app, but it shouldn't raise an error.
 * If you restore the original content of the Hello World startup script, and then add debug to output the environment, PATH, etc to the console: do you see any obvious differences between the in vs out of venv execution?

**Comment by jchenj** [comment]
> Another test: does running open /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app yield the same behavior, depending on whether you're inside or outside the virtual environment?

The app ran successfully both inside and outside the venv with `open /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app`

> If you change that script to a simple "echo hello" - does it run? (it obviously won't start the app, but it shouldn't raise an error.)

I changed the script to `echo hello` and tried `open /Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app`. It didn't run either inside or outside the venv ('echo' did not output). No error was generated most of the time, but every so often (e.g. after ~10 attempts) I got the same error as initially, both inside & outside of the venv.

````
jchen@ribka:~$ open "/Users/jchen/Desktop/FOSS/beeware/briefcase2/briefcase/src/
macOS/Hello World/Hello World.app"
LSOpenURLsWithRole() failed with error -10810 for the file /Users/jchen/Desktop/FOSS/
beeware/briefcase2/briefcase/src/macOS/Hello World/Hello World.app.
````

The edited script did output 'hello' when run directly:
````
(.env) jchen@ribka:~/Desktop/FOSS/beeware/briefcase2/briefcase$ /Users/jchen/Desktop/
FOSS/beeware/briefcase2/briefcase/src/macOS/Hello\ World/Hello\ World.app/Contents/
MacOS/Hello\ World 
hello
````
Based on the last set of experiments it looks like the error may not have anything to do with Python code. How does it seem to you?

**Comment by freakboy3742** [comment]
At this point, I'm thoroughly confused :-). If there's a pattern here in the failures, I'm not seeing it.

The only other thing I can think that might be influencing behavior here is the support package itself. We've recently published a new version of the macOS support package, and we've had some scattered reports of incompatibilities raising the same error you're reporting - which, on further investigation have been caused by a missing library dependency (usually libgettext).

I'm wondering if this might be the cause of the problem for you - and the virtual environment is (for some reason) altering the runtime environment enough that a library is (or isn't) visible to the running executable. 

Can you confirm:
(a) What version of the support library was used to build your app (you can confirm this with the contents of Hello World.app/Contents/Resources/Support/VERSIONS)
(b) If you rebuild the app using Briefcase 0.3.1 and the latest support package, does the same problem still occur?
(c) Do you have homebrew installed? (It appears that people with homebrew have slightly different behavior because of the extra libraries that homebrew provides).

**Comment by jchenj** [comment]
Answers for (a) & (c) are below. I'll get back to you on (b) shortly!  

> (a) What version of the support library was used to build your app?

Python version: 3.7.5 
Build: 2

BZip2: 1.0.8
OpenSSL: 1.1.1d
XZ: 5.2.4

> (c) Do you have homebrew installed? 

Yes, I have Homebrew 2.2.10 installed at /usr/local/bin/brew

**Comment by robinsiebler** [comment]
I am following the tutorial as well. Here is the error I get:
```
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/local/Dev/plexlibraryviewer/macOS/Plex Library Viewer/Plex Library Viewer.app/Contents/Resources/Support/bin/python3
  Reason: image not found
./macOS/Plex Library Viewer/Plex Library Viewer.app/Contents/MacOS/Plex Library Viewer: line 5:  4133 Abort trap: 6
```
If I copy libintl.8.dylib into the path specified (which didn't exist), it runs, but when I create the image and try to run the app on a different Mac, I get the same error. 

How do I fix this?

**Comment by freakboy3742** [comment]
@robinsiebler The error you're seeing looks like a flaw in the support package; we're aware of it, but need to find time to fix it. There's no simple fix I can recommend in the meantime; the closest you'll get is to build your own version of the macOS support package.

**Comment by robinsiebler** [comment]
Is there any kind of ETA for this fix? Soon, 3-6 months, or don’t hold your breath?

Also, I have another question:

	Toga doesn’t seem to have the ability to hide a table. I wanted to do this because the table is the main component of my main window, but...I won’t have any data for the table until the user makes a selection. So, is it possible to show the main window sans table and add it at a later point?

**Comment by robinsiebler** [comment]
Oh! Once last question, it is not toga specific, because I noticed the same issue when I tried to use PyQt5. When I run my app, the only way I can interact with the menu bar is to press Ctrl+F2 and use the arrow keys. The app does not react to the mouse.

**Comment by freakboy3742** [comment]
@robinsiebler Hopefully we'll have a fix very soon - I'd estimate no more than a week or two. It seems to be affecting a lot of people.

As for the other two issues you describe; it would be helpful if you either open them as separate tickets on the relevant repositories, or ask them on the chat room. This ticket is tracking one specific problem; I'd rather not muddy the diagnosis of that problem with unrelated problems.

**Comment by robinsiebler** [comment]
Will do! I didn't even know there **was** a chat room! Heading there now...

**Comment by jchenj** [comment]
@freakboy3742, to address item (b) in your list from June 21st ("If you rebuild the app using Briefcase 0.3.1 and the latest support package, does the same problem still occur?):

I went through the tutorial again from the beginning through Step 4 (i.e. created the initial & updated versions of the desktop MacOS desktop app). The short answer is I ran into the same problem (`briefcase run` failed with same error), with one difference (this time the the DMG installed copy for each version didn't run either). The app ran successfully in dev mode. Details below:

**`Briefcase run` error**
````
(.env) jchen@ribka:~/Desktop/FOSS/beeware/beeware-tutorial2/helloworld$ briefcase run

[helloworld] Starting app...

LSOpenURLsWithRole() failed with error -10810 for the file /Users/jchen/Desktop/FOSS/
beeware/beeware-tutorial2/helloworld/macOS/Hello World/Hello World.app.

Unable to start app helloworld.
````

**Installed app didn't start**
While the installed app ran fine when I first did the tutorial last month, this time it  didn't open on double-clicking the icon. I tried opening it with `./macOS/Hello\ World/Hello\ World.app/Contents/MacOS/Hello\ World` and got the following error:

````
(.env) jchen@ribka:~/Desktop/FOSS/beeware/beeware-tutorial2/helloworld$ ./macOS/
Hello\ World/Hello\ World.app/Contents/MacOS/Hello\ World
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/jchen/Desktop/FOSS/beeware/beeware-tutorial2/helloworld/
macOS/Hello World/Hello World.app/Contents/Resources/Support/bin/python3
  Reason: image not found
./macOS/Hello World/Hello World.app/Contents/MacOS/Hello World: line 5:  6169 
Abort trap: 6           
Support/bin/python3 -m helloworld

````
Is this the same error you mentioned other folks have been running into?  

For reference, the support library version for this run-through of the tutorial was:

Python version: 3.7.7 
Build: b3

BZip2: 1.0.8
OpenSSL: 1.1.1g
XZ: 5.2.5

**Comment by freakboy3742** [comment]
@robinsiebler @jchenj I've just published new versions of the support packages; could I get you to do a clean build and let me know if you're still seeing a problem?

**Comment by robinsiebler** [comment]
Sure!

**Comment by jchenj** [comment]
For me the clean build app failed on `briefcase run` with the same error I've been running into:

````
(.env) jchen@ribka:~/Desktop/FOSS/beeware/beeware-tutorial3/helloworld$ briefcase run

[helloworld] Starting app...

LSOpenURLsWithRole() failed with error -10810 for the file /Users/jchen/Desktop/FOSS/beeware/
beeware-tutorial3/helloworld/macOS/Hello World/Hello World.app.

Unable to start app helloworld.

````
The app ran successfully in both dev mode & installed on the desktop. 

For reference, the support library version used here was: 

Python version: 3.7.7 
Build: b4
BZip2: 1.0.8
OpenSSL: 1.1.1g
XZ: 5.2.5

**Comment by freakboy3742** [comment]
@jchenj Ok - that's promising that we're at least back to where we were :-)

At this point, it seems like the only thing that is actually different is *exactly* how the app is started. So, next test: what happens if you run:

    (venv) $ open macOS/Hello World/Hello World.app

from *inside* the virtual environment where `briefcase dev` works?

**Comment by jchenj** [comment]
@freakboy3742 The app ran successfully with `open macOS/Hello\ World/Hello\ World.app` 

Yup, at this point it does look like we're back to where we were :-)

**Comment by freakboy3742** [comment]
@jchenj Ok... I'm wracking my brain trying to work out what could be different between Python's `subprocess.run()` call, and the same thing executing from the command line...

Just confirming: when you ran `open macOS/Hello\ World/Hello\ World.app` - was that with the venv activated or deactivated? Does that distinction make any difference?

**Comment by jchenj** [comment]
@freakboy3742 The venv was activated when I ran `open macOS/Hello\ World/Hello\ World.app` yesterday. I just ran it again, once with venv deactivated & once activated, and the app ran successfully both times. 

You indicated earlier that homebrew might be the source of the issue ("It appears that people with homebrew have slightly different behavior because of the extra libraries that homebrew provides.") Would it be worthwhile for me to uninstall homebrew & try running again?

**Comment by freakboy3742** [comment]
@jchenj I mentioned Homebrew because the earlier support packages had some leakage of libraries; if you had homebrew installed, you wouldn't see the problem, but if you did, you'd see the same LSOpenURLsWithRole() error. My theory was that maybe something about the way Python is running on your machine was hiding the homebrew, causing a crash. I've since corrected the support package so this isn't happening, so this shouldn't be an issue any more.

So, where to next...

There's an outside chance that whatever is failing *might* be showing up in the console logs. The macOS `console` app contains a bunch of debugging information about apps running on your system. It's possible that when the LSOpenURLsWithRole() error is being reported, the console log will contain more information.

So: try starting up console, add a search for `Hello World` to the search bar (this will filter the results to just entries that match), and start the failing version of the app... and see what it tells you.

**Comment by liudonghua123** [comment]
I have a similar issue when I on my windows. I tried to add the following debug code to `beeware-venv\Lib\site-packages\briefcase\__main__.py`.

```python
def audit_hook(event, args):
    if event.startswith('subprocess'):
        print(f'subprocess {event=} {args=}')

sys.addaudithook(audit_hook)
```

And then I execute `briefcase run -u` again, and I noted this line of error.

```
subprocess event='subprocess.Popen' args=(None, '"D:\\code\\python\\beeware-tutorial\\helloworld\\windows\\msi\\Hello World\\src\\python\\pythonw.exe" -m helloworld', None, None)
```

The full log is belows.

```
[helloworld] Updating application code...
Installing src/helloworld...

[helloworld] Application updated.

[helloworld] Built windows\msi\Hello World

[helloworld] Starting app...

subprocess event='subprocess.Popen' args=(None, '"D:\\code\\python\\beeware-tutorial\\helloworld\\windows\\msi\\Hello World\\src\\python\\pythonw.exe" -m helloworld', None, None)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\code\python\beeware-tutorial\beeware-venv\Scripts\briefcase.exe\__main__.py", line 7, in <module>
  File "d:\code\python\beeware-tutorial\beeware-venv\lib\site-packages\briefcase\__main__.py", line 17, in main
    command(**options)
  File "d:\code\python\beeware-tutorial\beeware-venv\lib\site-packages\briefcase\commands\run.py", line 77, in __call__
    state = self.run_app(app, **full_options(state, options))
  File "d:\code\python\beeware-tutorial\beeware-venv\lib\site-packages\briefcase\platforms\windows\msi.py", line 144, in run_app
    self.subprocess.run(
  File "d:\code\python\beeware-tutorial\beeware-venv\lib\site-packages\briefcase\integrations\subprocess.py", line 62, in run
    return self._subprocess.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

It's ok when execute `briefcase dev`. What's the difference of [`run`](https://briefcase.readthedocs.io/en/latest/reference/commands/run.html) and [`dev`](https://briefcase.readthedocs.io/en/latest/reference/commands/dev.html)?

**Comment by freakboy3742** [comment]
@liudonghua123 The bug you're describing is fundamentally different to the one from this ticket - for starters, you're not on the same operating system. 

However - there's a couple of differences between `run` and `dev`; most notably, `dev` executes in your development virtual environment, and `run` executes in the standalone app environment that Briefcase has constructed. 

The stack trace you've provided is highly suspicious, because it *doesn't* appear to be using the Briefcase packaged Python - it's picked up a version in your WindowsApps folder. The directory structure it's referencing is unfamiliar to me - what can you tell me about your Python installation? Where did you obtain the Python version that you're using? What configuration properties exist in the environment (e.g., `PYTHONPATH` settings)?

**Comment by liudonghua123** [comment]
@freakboy3742 Hi, thanks for your explanation. I installed the latest python 3.9.3 from ms app store. And I did not set any environment variables after installation. Then I create a directory `d:\code\python\beeware-tutorial` and start the tutorial on https://beeware.org/project/using/.

The following are the commands I executed.
```
cd d:\code\python
md beeware-tutorial
cd beeware-tutorial
py -m venv beeware-venv
beeware-venv\Scripts\activate.bat
python -m pip install briefcase
briefcase new
cd helloworld
briefcase dev
briefcase run -u
```

I read https://docs.beeware.org/en/latest/tutorial/tutorial-3.html again. Maybe I missed `briefcase create && briefcase build` before `briefcase run`.

When I executed `briefcase create`, I noted that a new directory `\windows\msi\Hello World\src\python` was created which contained `python.exe`. Now I executed `briefcase run -u` without the error mentioned above.

Thanks again! :smile:

**Comment by freakboy3742** [comment]
@jchenj It's been a while, but I was doing some housekeeping of issues and something occurred to me: this might be caused by app signing. I'm not sure why it would be affecting you specifically, but it's a possibility. We've also added some extra debugging assistance in Briefcase 0.3.6 that might help narrow this down. 

So:

1. Are you still able to reproduce this problem?

2. If so, if you run `briefcase package -p app --adhoc-sign` and then run `briefcase run` - do you still see the problem?

3. If that doesn't work - does the new log stream provided when the app starts provide any more useful context?

**Comment by freakboy3742** [comment]
Closing this due to lack of activity; if it turns out this is still an issue, I'm happy to re-open.

**Comment by taw-pi** [comment]
Hi, I have the same problem, running briefcase on MacOS 10.15.7 using Python 3.11.4. 

In trying to run the app via Finder I get an error from Mac indicating that I can't use this version of the application "Hello World.app" with this version of MacOS. 'You have macOS 10.15.7. The application requires macOS 11.0 or later' ??

I wonder if this error message provides further information. I did look in the documentation to see if the OS version for the build could be specified but it looks like not.

**Comment by freakboy3742** [comment]
@taw-pi I'm not sure I understand what part of the error message you're receiving is unclear. 

You have macOS 10.15.7. 

The application requires macOS 11. 

This isn't something that is easily user-configurable - there are certain properties of macOS apps that changed significantly with macOS 11, as this was the release that introduced ARM64 support.

You *might* be able to generate an x86_64-only app by modifying the Info.plist file in the generated app to set a lower required version, and by setting the [`universal_build=False`](https://briefcase.readthedocs.io/en/stable/reference/platforms/macOS/app.html#universal-build) option in your `pyproject.toml`. However, that depends on your underlying GUI framework supporting macOS 10.15 or earlier. Toga, for example has a macOS 11 minimum.
